# Generated by obsidian
.incbin "/home/xor/Downloads/sandsand.png"

model_vertex_0:
vertex 350, -350, 350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #1
vertex -350, -350, -350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #2
vertex 350, -350, -350,    	0, 0,    	255, 255, 255, 255  		# VERTEX #3
vertex -350, 350, -350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #4
vertex 349, 350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #5
vertex 350, 350, -349,    	0, 0,    	255, 255, 255, 255  		# VERTEX #6
vertex 350, 350, -349,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #7
vertex 350, -350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #8
vertex 350, -350, -350,    	0, 0,    	255, 255, 255, 255  		# VERTEX #9
vertex 349, 350, 350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #10
vertex -350, -350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #11
vertex 350, -350, 350,    	0, 0,    	255, 255, 255, 255  		# VERTEX #12
vertex -350, -350, 350,    	0, 0,    	255, 255, 255, 255  		# VERTEX #13
vertex -350, 350, -350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #14
vertex -350, -350, -350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #15

model_vertex_1:
vertex 350, -350, -350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #16
vertex -350, 350, -350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #17
vertex 350, 350, -349,    	0, 0,    	255, 255, 255, 255  		# VERTEX #18
vertex 350, -350, 350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #19
vertex -350, -350, 350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #20
vertex -350, -350, -350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #21
vertex -350, 350, -350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #22
vertex -350, 350, 350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #23
vertex 349, 350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #24
vertex 350, 350, -349,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #25
vertex 349, 350, 350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #26
vertex 350, -350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #27
vertex 349, 350, 350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #28
vertex -350, 350, 350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #29
vertex -350, -350, 350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #30

model_vertex_2:
vertex -350, -350, 350,    	0, 0,    	255, 255, 255, 255  		# VERTEX #31
vertex -350, 350, 350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #32
vertex -350, 350, -350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #33
vertex 350, -350, -350,    	1024, 0,    	255, 255, 255, 255  		# VERTEX #34
vertex -350, -350, -350,    	1024, 1024,    	255, 255, 255, 255  		# VERTEX #35
vertex -350, 350, -350,    	0, 1024,    	255, 255, 255, 255  		# VERTEX #36

glabel model_dl
gsSPVertex model_vertex_0 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex model_vertex_1 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex model_vertex_2 6, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
