# Generated by modconv 2

.hword 0x0040, 72
.hword -350, -350, -350
.hword -350, 350, -350
.hword -350, 350, 350
.hword -350, -350, 350
.hword -350, -350, 350
.hword -350, 350, 350
.hword 350, 350, 350
.hword 350, -350, 350
.hword 350, -350, 350
.hword 350, 350, 350
.hword 350, 350, -350
.hword 350, -350, -350
.hword 350, -350, -350
.hword 350, 350, -350
.hword -350, 350, -350
.hword -350, -350, -350
.hword -350, -350, 350
.hword 350, -350, 350
.hword 350, -350, -350
.hword -350, -350, -350
.hword 350, 350, 350
.hword -350, 350, 350
.hword -350, 350, -350
.hword 350, 350, -350
.hword -5600, 350, 1400
.hword -5600, 1050, 1400
.hword -5600, 1050, 2100
.hword -5600, 350, 2100
.hword -5600, 350, 2100
.hword -5600, 1050, 2100
.hword -4900, 1050, 2100
.hword -4900, 350, 2100
.hword -4900, 350, 2100
.hword -4900, 1050, 2100
.hword -4900, 1050, 1400
.hword -4900, 350, 1400
.hword -4900, 350, 1400
.hword -4900, 1050, 1400
.hword -5600, 1050, 1400
.hword -5600, 350, 1400
.hword -5600, 350, 2100
.hword -4900, 350, 2100
.hword -4900, 350, 1400
.hword -5600, 350, 1400
.hword -4900, 1050, 2100
.hword -5600, 1050, 2100
.hword -5600, 1050, 1400
.hword -4900, 1050, 1400
.hword -4550, -350, -2100
.hword -4550, 350, -2100
.hword -4550, 350, -1400
.hword -4550, -350, -1400
.hword -4550, -350, -1400
.hword -4550, 350, -1400
.hword -3850, 350, -1400
.hword -3850, -350, -1400
.hword -3850, -350, -1400
.hword -3850, 350, -1400
.hword -3850, 350, -2100
.hword -3850, -350, -2100
.hword -3850, -350, -2100
.hword -3850, 350, -2100
.hword -4550, 350, -2100
.hword -4550, -350, -2100
.hword -4550, -350, -1400
.hword -3850, -350, -1400
.hword -3850, -350, -2100
.hword -4550, -350, -2100
.hword -3850, 350, -1400
.hword -4550, 350, -1400
.hword -4550, 350, -2100
.hword -3850, 350, -2100

colTrisInit SURF_ENV_DEFAULT 6
colTri 0, 1, 2
colTri 4, 5, 6
colTri 8, 9, 10
colTri 12, 13, 14
colTri 16, 17, 18
colTri 20, 21, 22

colTrisInit SURF_ENV_DEFAULT 6
colTri 24, 25, 26
colTri 28, 29, 30
colTri 32, 33, 34
colTri 36, 37, 38
colTri 40, 41, 42
colTri 44, 45, 46

colTrisInit SURF_ENV_DEFAULT 6
colTri 48, 49, 50
colTri 52, 53, 54
colTri 56, 57, 58
colTri 60, 61, 62
colTri 64, 65, 66
colTri 68, 69, 70

.word 0x0041
.hword 0x0042
