# Generated by modconv 2
include "collision.inc"

glabel model_collision
colInit
colVertexInit 72
colVertex -350, -350, -350
colVertex -350, 350, -350
colVertex -350, 350, 350
colVertex -350, -350, 350
colVertex -350, -350, 350
colVertex -350, 350, 350
colVertex 350, 350, 350
colVertex 350, -350, 350
colVertex 350, -350, 350
colVertex 350, 350, 350
colVertex 350, 350, -350
colVertex 350, -350, -350
colVertex 350, -350, -350
colVertex 350, 350, -350
colVertex -350, 350, -350
colVertex -350, -350, -350
colVertex -350, -350, 350
colVertex 350, -350, 350
colVertex 350, -350, -350
colVertex -350, -350, -350
colVertex 350, 350, 350
colVertex -350, 350, 350
colVertex -350, 350, -350
colVertex 350, 350, -350
colVertex -5600, 350, 1400
colVertex -5600, 1050, 1400
colVertex -5600, 1050, 2100
colVertex -5600, 350, 2100
colVertex -5600, 350, 2100
colVertex -5600, 1050, 2100
colVertex -4900, 1050, 2100
colVertex -4900, 350, 2100
colVertex -4900, 350, 2100
colVertex -4900, 1050, 2100
colVertex -4900, 1050, 1400
colVertex -4900, 350, 1400
colVertex -4900, 350, 1400
colVertex -4900, 1050, 1400
colVertex -5600, 1050, 1400
colVertex -5600, 350, 1400
colVertex -5600, 350, 2100
colVertex -4900, 350, 2100
colVertex -4900, 350, 1400
colVertex -5600, 350, 1400
colVertex -4900, 1050, 2100
colVertex -5600, 1050, 2100
colVertex -5600, 1050, 1400
colVertex -4900, 1050, 1400
colVertex -4550, -350, -2100
colVertex -4550, 350, -2100
colVertex -4550, 350, -1400
colVertex -4550, -350, -1400
colVertex -4550, -350, -1400
colVertex -4550, 350, -1400
colVertex -3850, 350, -1400
colVertex -3850, -350, -1400
colVertex -3850, -350, -1400
colVertex -3850, 350, -1400
colVertex -3850, 350, -2100
colVertex -3850, -350, -2100
colVertex -3850, -350, -2100
colVertex -3850, 350, -2100
colVertex -4550, 350, -2100
colVertex -4550, -350, -2100
colVertex -4550, -350, -1400
colVertex -3850, -350, -1400
colVertex -3850, -350, -2100
colVertex -4550, -350, -2100
colVertex -3850, 350, -1400
colVertex -4550, 350, -1400
colVertex -4550, 350, -2100
colVertex -3850, 350, -2100

colTriInit SURF_ENV_DEFAULT 6
colTri 0, 1, 2
colTri 4, 5, 6
colTri 8, 9, 10
colTri 12, 13, 14
colTri 16, 17, 18
colTri 20, 21, 22

colTriInit SURF_ENV_DEFAULT 6
colTri 24, 25, 26
colTri 28, 29, 30
colTri 32, 33, 34
colTri 36, 37, 38
colTri 40, 41, 42
colTri 44, 45, 46

colTriInit SURF_ENV_DEFAULT 6
colTri 48, 49, 50
colTri 52, 53, 54
colTri 56, 57, 58
colTri 60, 61, 62
colTri 64, 65, 66
colTri 68, 69, 70

colTriStop
colEnd
