/* Generated by modconv 2 */

glabel model_geo
    geo_shadow SHADOW_CIRCLE_4_VERTS, 0xC8, 60
        geo_open_node
            geo_scale 0x00, 16384
            geo_open_node
                geo_display_list LAYER_OPAQUE model_dl_opaque
            geo_close_node
        geo_close_node
    geo_end
