# Generated by modconv 2

hmc_textures.06800.rgba16:
.incbin "hmc_textures.06800.rgba16"

wf_textures.07800.rgba16:
.incbin "wf_textures.07800.rgba16"

model_vertex_0:
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255

model_vertex_1:
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 1400, 0, 0, 255, 255, 255, 255

model_vertex_2:
vertex -5600, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 2100, 0, 0, 255, 255, 255, 255
vertex -4900, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -5600, 350, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 2100, 0, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4900, 1050, 1400, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -2100, 0, 0, 255, 255, 255, 255

model_vertex_3:
vertex -3850, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -1400, 0, 0, 255, 255, 255, 255
vertex -3850, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -4550, -350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -1400, 0, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 0, 0, 255, 255, 255, 255
vertex -3850, 350, -2100, 0, 0, 255, 255, 255, 255

glabel model_dl
gsSPClearGeometryMode G_LIGHTING
gsSPVertex model_vertex_0 30, 0
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock hmc_textures.06800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSP1Triangle 15 16 17
gsSP1Triangle 18 19 20
gsSP1Triangle 21 22 23
gsSP1Triangle 24 25 26
gsSP1Triangle 27 28 29
gsSPVertex model_vertex_1 30, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock wf_textures.07800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSP1Triangle 15 16 17
gsSP1Triangle 18 19 20
gsSP1Triangle 21 22 23
gsSP1Triangle 24 25 26
gsSP1Triangle 27 28 29
gsSPVertex model_vertex_2 30, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock hmc_textures.06800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSP1Triangle 12 13 14
gsSP1Triangle 15 16 17
gsSP1Triangle 18 19 20
gsSP1Triangle 21 22 23
gsSP1Triangle 24 25 26
gsSP1Triangle 27 28 29
gsSPVertex model_vertex_3 18, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSP1Triangle 15 16 17
gsSPEndDisplayList
