/* Generated by modconv 2 */

Ambient model_ambient_light = {
{{0x66, 0x66, 0x66}, 0x00, {0x66, 0x66, 0x66}, 0x00}
};
Light model_diffuse_light = {
{{0xff, 0xff, 0xff}, 0x00, {0xff, 0xff, 0xff}, 0x00, {0x28, 0x28, 0x28}, 0x00}
};

ALIGNED8 u8 model_texture_1[] = {
#include "actors/model/gold-block-big.rgba16.inc.c"
};

Vtx model_vertex_0[11] = { /* 11 vertices out of 15 */
    {{{   3500,    349,  -3500}, 0x00, {      0,      0}, {0x00, 0x7f, 0x00, 0xff}}},
    {{{  -3500,    349,  -3500}, 0x00, {      0,      0}, {0x00, 0x7f, 0x00, 0xff}}},
    {{{  -3500,    350,   3500}, 0x00, {      0,      0}, {0x00, 0x7f, 0x00, 0xff}}},
    {{{   3500,    350,   3500}, 0x00, {      0,      0}, {0x00, 0x7f, 0x00, 0xff}}},
    {{{   3500,   -349,   3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x7f, 0xff}}},
    {{{   3500,    350,   3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x7f, 0xff}}},
    {{{  -3500,    350,   3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x7f, 0xff}}},
    {{{  -3500,   -349,   3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x7f, 0xff}}},
    {{{  -3500,   -349,   3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
    {{{  -3500,    350,   3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
    {{{  -3500,    349,  -3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
};

Vtx model_vertex_1[11] = { /* 11 vertices out of 15 */
    {{{  -3500,   -349,   3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
    {{{  -3500,    349,  -3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
    {{{  -3500,   -350,  -3500}, 0x00, {      0,      0}, {0x81, 0x00, 0x00, 0xff}}},
    {{{  -3500,   -350,  -3500}, 0x00, {      0,      0}, {0x00, 0x81, 0x00, 0xff}}},
    {{{   3500,   -350,  -3500}, 0x00, {      0,      0}, {0x00, 0x81, 0x00, 0xff}}},
    {{{   3500,   -349,   3500}, 0x00, {      0,      0}, {0x00, 0x81, 0x00, 0xff}}},
    {{{  -3500,   -349,   3500}, 0x00, {      0,      0}, {0x00, 0x81, 0x00, 0xff}}},
    {{{   3500,   -350,  -3500}, 0x00, {      0,      0}, {0x7f, 0x00, 0x00, 0xff}}},
    {{{   3500,    349,  -3500}, 0x00, {      0,      0}, {0x7f, 0x00, 0x00, 0xff}}},
    {{{   3500,    350,   3500}, 0x00, {      0,      0}, {0x7f, 0x00, 0x00, 0xff}}},
    {{{   3500,   -349,   3500}, 0x00, {      0,      0}, {0x7f, 0x00, 0x00, 0xff}}},
};

Vtx model_vertex_2[11] = { /* 11 vertices out of 15 */
    {{{  -3500,   -350,  -3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x81, 0xff}}},
    {{{  -3500,    349,  -3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x81, 0xff}}},
    {{{   3500,    349,  -3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x81, 0xff}}},
    {{{   3500,   -350,  -3500}, 0x00, {      0,      0}, {0x00, 0x00, 0x81, 0xff}}},
    {{{   -350,    350,    350}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,    349}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,   -350}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,    349,   -349}, 0x00, {    992,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,    349,   -349}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,   -350}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,   -350}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
};

Vtx model_vertex_3[9] = { /* 9 vertices out of 15 */
    {{{   -350,    349,   -349}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,   -350}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,    349,   -349}, 0x00, {    992,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,    349}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,    350,    350}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,    350,    350}, 0x00, {    992,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,    349}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,    349}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,    350,    350}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
};

Vtx model_vertex_4[8] = { /* 8 vertices out of 12 */
    {{{   -350,    349,   -349}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,    349,   -349}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,    350,    350}, 0x00, {    992,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,    350,    350}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,   -350}, 0x00, {    992,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,   -350}, 0x00, {    -32,  -1056}, {0xff, 0xff, 0xff, 0xff}}},
    {{{   -350,   1050,    349}, 0x00, {    -32,    -32}, {0xff, 0xff, 0xff, 0xff}}},
    {{{    350,   1050,    349}, 0x00, {    992,    -32}, {0xff, 0xff, 0xff, 0xff}}},
};

/* Render order: 1 */
Gfx model_dl_opaque[] = {
    gsSPClearGeometryMode(G_LIGHTING),
    /* Material.002 #LIGHTING */
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_LIGHTING),
    gsSPNumLights(NUMLIGHTS_1),
    gsSPLight(&model_diffuse_light, 1),
    gsSPLight(&model_ambient_light, 2),
    gsDPSetCombineMode(G_CC_SHADE, G_CC_SHADE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPTexture(0xFFFF, 0xFFFF, 0, 0, G_ON),
    gsDPTileSync(),
    gsSPVertex(model_vertex_0, 11, 0),
    gsSP2Triangles(0, 1, 2, 0x00, 0, 2, 3, 0x00),
    gsSP2Triangles(4, 5, 6, 0x00, 4, 6, 7, 0x00),
    gsSP1Triangle(8, 9, 10, 0x00),
    gsSPVertex(model_vertex_1, 11, 0),
    gsSP2Triangles(0, 1, 2, 0x00, 3, 4, 5, 0x00),
    gsSP2Triangles(3, 5, 6, 0x00, 7, 8, 9, 0x00),
    gsSP1Triangle(7, 9, 10, 0x00),
    gsSPVertex(model_vertex_2, 11, 0),
    gsSP2Triangles(0, 1, 2, 0x00, 0, 2, 3, 0x00),
    /* Material.001 */
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_LIGHTING),
    gsDPSetCombineMode(G_CC_MODULATERGB, G_CC_MODULATERGB),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureBlock(&model_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPTileSync(),
    gsSP2Triangles(4, 5, 6, 0x00, 4, 6, 7, 0x00),
    gsSP1Triangle(8, 9, 10, 0x00),
    gsSPVertex(model_vertex_3, 9, 0),
    gsSP2Triangles(0, 1, 2, 0x00, 2, 1, 3, 0x00),
    gsSP2Triangles(2, 3, 4, 0x00, 5, 6, 7, 0x00),
    gsSP1Triangle(5, 7, 8, 0x00),
    gsSPVertex(model_vertex_4, 8, 0),
    gsSP2Triangles(0, 1, 2, 0x00, 0, 2, 3, 0x00),
    gsSP2Triangles(4, 5, 6, 0x00, 4, 6, 7, 0x00),
    gsSPTexture(0xFFFF, 0xFFFF, 0, 0, G_OFF),
    gsDPPipeSync(),
    gsDPSetCombineMode(G_CC_SHADE, G_CC_SHADE),
    gsSPSetGeometryMode(G_LIGHTING),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPEndDisplayList(),
};
