# Generated by modconv 2

model_vertex_0:
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255

model_vertex_1:
vertex 350, -350, 350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, -350, 0, 0, 255, 255, 255, 255
vertex -350, -350, 350, 0, 0, 255, 255, 255, 255

model_vertex_2:
vertex 350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, 350, 0, 0, 255, 255, 255, 255
vertex -350, 350, -350, 0, 0, 255, 255, 255, 255
vertex 350, 350, -350, 0, 0, 255, 255, 255, 255

glabel model_dl
gsSPClearGeometryMode G_LIGHTING
gsSPVertex model_vertex_0 15, 0
/* DEFAULT MATERIAL */
gsDPSetCombineMode1Cycle G_CCMUX_PRIMITIVE, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetPrimColor 0x00, 0x00, 128, 128, 128, 0xFF
gsSP2Triangles 2, 1, 0, 0x00, 5, 4, 3, 0x00
gsSP2Triangles 8, 7, 6, 0x00, 11, 10, 9, 0x00
gsSP1Triangle 14, 13, 12, 0x00
gsSPVertex model_vertex_1 15, 0
gsSP2Triangles 2, 1, 0, 0x00, 5, 4, 3, 0x00
gsSP2Triangles 8, 7, 6, 0x00, 11, 10, 9, 0x00
gsSP1Triangle 14, 13, 12, 0x00
gsSPVertex model_vertex_2 6, 0
gsSP2Triangles 2, 1, 0, 0x00, 5, 4, 3, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineMode1Cycle G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsSPEndDisplayList
