/* Generated by modconv 2 */

extern Vtx model_vertex_0[11];
extern Vtx model_vertex_1[11];
extern Vtx model_vertex_2[11];
extern Vtx model_vertex_3[9];
extern Vtx model_vertex_4[8];
extern Gfx model_dl_opaque;

