# Generated by modconv 2

model_vertex_0:
vertex -350, -350, -350, 384, 0, 255, 255, 255, 255
vertex -350, 350, -350, 640, 0, 255, 255, 255, 255
vertex -350, 350, 350, 640, 256, 255, 255, 255, 255
vertex -350, -350, -350, 384, 0, 255, 255, 255, 255
vertex -350, 350, 350, 640, 256, 255, 255, 255, 255
vertex -350, -350, 350, 384, 256, 255, 255, 255, 255
vertex -350, -350, 350, 384, 256, 255, 255, 255, 255
vertex -350, 350, 350, 640, 256, 255, 255, 255, 255
vertex 350, 350, 350, 640, 512, 255, 255, 255, 255
vertex -350, -350, 350, 384, 256, 255, 255, 255, 255
vertex 350, 350, 350, 640, 512, 255, 255, 255, 255
vertex 350, -350, 350, 384, 512, 255, 255, 255, 255
vertex 350, -350, 350, 384, 512, 255, 255, 255, 255
vertex 350, 350, 350, 640, 512, 255, 255, 255, 255
vertex 350, 350, -350, 640, 768, 255, 255, 255, 255

model_vertex_1:
vertex 350, -350, 350, 384, 512, 255, 255, 255, 255
vertex 350, 350, -350, 640, 768, 255, 255, 255, 255
vertex 350, -350, -350, 384, 768, 255, 255, 255, 255
vertex 350, -350, -350, 384, 768, 255, 255, 255, 255
vertex 350, 350, -350, 640, 768, 255, 255, 255, 255
vertex -350, 350, -350, 640, 1024, 255, 255, 255, 255
vertex 350, -350, -350, 384, 768, 255, 255, 255, 255
vertex -350, 350, -350, 640, 1024, 255, 255, 255, 255
vertex -350, -350, -350, 384, 1024, 255, 255, 255, 255
vertex -350, -350, 350, 128, 512, 255, 255, 255, 255
vertex 350, -350, 350, 384, 512, 255, 255, 255, 255
vertex 350, -350, -350, 384, 768, 255, 255, 255, 255
vertex -350, -350, 350, 128, 512, 255, 255, 255, 255
vertex 350, -350, -350, 384, 768, 255, 255, 255, 255
vertex -350, -350, -350, 128, 768, 255, 255, 255, 255

model_vertex_2:
vertex 350, 350, 350, 640, 512, 255, 255, 255, 255
vertex -350, 350, 350, 896, 512, 255, 255, 255, 255
vertex -350, 350, -350, 896, 768, 255, 255, 255, 255
vertex 350, 350, 350, 640, 512, 255, 255, 255, 255
vertex -350, 350, -350, 896, 768, 255, 255, 255, 255
vertex 350, 350, -350, 640, 768, 255, 255, 255, 255
vertex -5600, 350, 1400, 384, 0, 255, 255, 255, 255
vertex -5600, 1050, 1400, 640, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 640, 256, 255, 255, 255, 255
vertex -5600, 350, 1400, 384, 0, 255, 255, 255, 255
vertex -5600, 1050, 2100, 640, 256, 255, 255, 255, 255
vertex -5600, 350, 2100, 384, 256, 255, 255, 255, 255
vertex -5600, 350, 2100, 384, 256, 255, 255, 255, 255
vertex -5600, 1050, 2100, 640, 256, 255, 255, 255, 255
vertex -4900, 1050, 2100, 640, 512, 255, 255, 255, 255

model_vertex_3:
vertex -5600, 350, 2100, 384, 256, 255, 255, 255, 255
vertex -4900, 1050, 2100, 640, 512, 255, 255, 255, 255
vertex -4900, 350, 2100, 384, 512, 255, 255, 255, 255
vertex -4900, 350, 2100, 384, 512, 255, 255, 255, 255
vertex -4900, 1050, 2100, 640, 512, 255, 255, 255, 255
vertex -4900, 1050, 1400, 640, 768, 255, 255, 255, 255
vertex -4900, 350, 2100, 384, 512, 255, 255, 255, 255
vertex -4900, 1050, 1400, 640, 768, 255, 255, 255, 255
vertex -4900, 350, 1400, 384, 768, 255, 255, 255, 255
vertex -4900, 350, 1400, 384, 768, 255, 255, 255, 255
vertex -4900, 1050, 1400, 640, 768, 255, 255, 255, 255
vertex -5600, 1050, 1400, 640, 1024, 255, 255, 255, 255
vertex -4900, 350, 1400, 384, 768, 255, 255, 255, 255
vertex -5600, 1050, 1400, 640, 1024, 255, 255, 255, 255
vertex -5600, 350, 1400, 384, 1024, 255, 255, 255, 255

model_vertex_4:
vertex -5600, 350, 2100, 128, 512, 255, 255, 255, 255
vertex -4900, 350, 2100, 384, 512, 255, 255, 255, 255
vertex -4900, 350, 1400, 384, 768, 255, 255, 255, 255
vertex -5600, 350, 2100, 128, 512, 255, 255, 255, 255
vertex -4900, 350, 1400, 384, 768, 255, 255, 255, 255
vertex -5600, 350, 1400, 128, 768, 255, 255, 255, 255
vertex -4900, 1050, 2100, 640, 512, 255, 255, 255, 255
vertex -5600, 1050, 2100, 896, 512, 255, 255, 255, 255
vertex -5600, 1050, 1400, 896, 768, 255, 255, 255, 255
vertex -4900, 1050, 2100, 640, 512, 255, 255, 255, 255
vertex -5600, 1050, 1400, 896, 768, 255, 255, 255, 255
vertex -4900, 1050, 1400, 640, 768, 255, 255, 255, 255
vertex -4550, -350, -2100, 384, 0, 255, 255, 255, 255
vertex -4550, 350, -2100, 640, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 640, 256, 255, 255, 255, 255

model_vertex_5:
vertex -4550, -350, -2100, 384, 0, 255, 255, 255, 255
vertex -4550, 350, -1400, 640, 256, 255, 255, 255, 255
vertex -4550, -350, -1400, 384, 256, 255, 255, 255, 255
vertex -4550, -350, -1400, 384, 256, 255, 255, 255, 255
vertex -4550, 350, -1400, 640, 256, 255, 255, 255, 255
vertex -3850, 350, -1400, 640, 512, 255, 255, 255, 255
vertex -4550, -350, -1400, 384, 256, 255, 255, 255, 255
vertex -3850, 350, -1400, 640, 512, 255, 255, 255, 255
vertex -3850, -350, -1400, 384, 512, 255, 255, 255, 255
vertex -3850, -350, -1400, 384, 512, 255, 255, 255, 255
vertex -3850, 350, -1400, 640, 512, 255, 255, 255, 255
vertex -3850, 350, -2100, 640, 768, 255, 255, 255, 255
vertex -3850, -350, -1400, 384, 512, 255, 255, 255, 255
vertex -3850, 350, -2100, 640, 768, 255, 255, 255, 255
vertex -3850, -350, -2100, 384, 768, 255, 255, 255, 255

model_vertex_6:
vertex -3850, -350, -2100, 384, 768, 255, 255, 255, 255
vertex -3850, 350, -2100, 640, 768, 255, 255, 255, 255
vertex -4550, 350, -2100, 640, 1024, 255, 255, 255, 255
vertex -3850, -350, -2100, 384, 768, 255, 255, 255, 255
vertex -4550, 350, -2100, 640, 1024, 255, 255, 255, 255
vertex -4550, -350, -2100, 384, 1024, 255, 255, 255, 255
vertex -4550, -350, -1400, 128, 512, 255, 255, 255, 255
vertex -3850, -350, -1400, 384, 512, 255, 255, 255, 255
vertex -3850, -350, -2100, 384, 768, 255, 255, 255, 255
vertex -4550, -350, -1400, 128, 512, 255, 255, 255, 255
vertex -3850, -350, -2100, 384, 768, 255, 255, 255, 255
vertex -4550, -350, -2100, 128, 768, 255, 255, 255, 255
vertex -3850, 350, -1400, 640, 512, 255, 255, 255, 255
vertex -4550, 350, -1400, 896, 512, 255, 255, 255, 255
vertex -4550, 350, -2100, 896, 768, 255, 255, 255, 255

model_vertex_7:
vertex -3850, 350, -1400, 640, 512, 255, 255, 255, 255
vertex -4550, 350, -2100, 896, 768, 255, 255, 255, 255
vertex -3850, 350, -2100, 640, 768, 255, 255, 255, 255

glabel model_dl
gsSPClearGeometryMode G_LIGHTING
gsSPVertex model_vertex_0 15, 0
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock hmc_textures.06800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_1 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_2 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock wf_textures.07800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_3 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_4 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsDPSetCombineMode G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_COMBINED, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_COMBINED
gsDPLoadTextureBlock hmc_textures.06800.rgba16, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture -1, -1, 0, 0, 1
gsDPTileSync
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_5 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_6 15, 0
gsSP1Triangle 0 1 2
gsSP1Triangle 3 4 5
gsSP1Triangle 6 7 8
gsSP1Triangle 9 10 11
gsSP1Triangle 12 13 14
gsSPVertex model_vertex_7 3, 0
gsSP1Triangle 0 1 2
gsSPEndDisplayList
