# Generated by modconv 2
ss_colored_stone_tiles.ci4_pal:
.incbin "ss_colored_stone_tiles.ci4.pal"
ss_metal_patch.ci4_pal:
.incbin "ss_metal_patch.ci4.pal"
ss_tiled_floor.ci4_pal:
.incbin "ss_tiled_floor.ci4.pal"
