/* Generated by modconv 2 */

glabel bob_collision
colInit
colVertexInit 16
colVertex   3500,    349,  -3500
colVertex  -3500,    349,  -3500
colVertex  -3500,    350,   3500
colVertex   3500,    350,   3500
colVertex   3500,   -349,   3500
colVertex  -3500,   -349,   3500
colVertex  -3500,   -350,  -3500
colVertex   3500,   -350,  -3500
colVertex   -350,    350,    350
colVertex   -350,   1050,    349
colVertex   -350,   1050,   -350
colVertex   -350,    349,   -349
colVertex    350,   1050,   -350
colVertex    350,    349,   -349
colVertex    350,   1050,    349
colVertex    350,    350,    350

colTriInit SURFACE_DEFAULT, 12
colTri      0,      1,      2
colTri      0,      2,      3
colTri      4,      3,      2
colTri      4,      2,      5
colTri      5,      2,      1
colTri      5,      1,      6
colTri      6,      7,      4
colTri      6,      4,      5
colTri      7,      0,      3
colTri      7,      3,      4
colTri      6,      1,      0
colTri      6,      0,      7

colTriInit SURFACE_DEFAULT, 12
colTri      8,      9,     10
colTri      8,     10,     11
colTri     11,     10,     12
colTri     11,     12,     13
colTri     13,     12,     14
colTri     13,     14,     15
colTri     15,     14,      9
colTri     15,      9,      8
colTri     11,     13,     15
colTri     11,     15,      8
colTri     12,     10,      9
colTri     12,      9,     14
colTriStop
colEnd
