/* Generated by modconv 2 */

const s16 bob_collision[] = {
    COL_INIT(),
    COL_VERTEX_INIT(8),
    COL_VERTEX(  6509,  -2134,  -6509),
    COL_VERTEX( -6509,  -2135,  -6509),
    COL_VERTEX( -6509,  -2135,   6509),
    COL_VERTEX(  6509,  -2134,   6509),
    COL_VERTEX(  6509,  -2064,   6509),
    COL_VERTEX( -6509,  -2065,   6509),
    COL_VERTEX( -6509,  -2065,  -6509),
    COL_VERTEX(  6509,  -2064,  -6509),

    COL_TRI_INIT(SURFACE_DEFAULT, 12),
    COL_TRI(     0,      1,      2),
    COL_TRI(     0,      2,      3),
    COL_TRI(     4,      3,      2),
    COL_TRI(     4,      2,      5),
    COL_TRI(     5,      2,      1),
    COL_TRI(     5,      1,      6),
    COL_TRI(     6,      7,      4),
    COL_TRI(     6,      4,      5),
    COL_TRI(     7,      0,      3),
    COL_TRI(     7,      3,      4),
    COL_TRI(     6,      1,      0),
    COL_TRI(     6,      0,      7),
    COL_TRI_STOP(),
    COL_WATERBOX_INIT(1),
    COL_WATER_BOX( 0,  -6509,  -6509,   6509,   6509,      0),
    COL_END()
};
