/* Generated by modconv 2 */

wooden_signpost_ambient_light:
.byte 0x66, 0x66, 0x66, 0x00, 0x66, 0x66, 0x66, 0x00
wooden_signpost_diffuse_light:
.byte 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0x00
.byte 0x28, 0x28, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00

wooden_signpost_texture_0:
.incbin "actors/wooden_signpost/g.rgba16"

wooden_signpost_texture_1:
.incbin "actors/wooden_signpost/r.rgba16"

wooden_signpost_texture_2:
.incbin "actors/wooden_signpost/b.rgba16"

wooden_signpost_texture_3:
.incbin "actors/wooden_signpost/y.rgba16"

wooden_signpost_vertex_0: /* 20 vertices out of 30 */
vertex   -335,   2051,    111,   -277,  -1791,   0x00, 0x00, 0x82, 0xff
vertex   -335,   2322,    111,   -277,  -2205,   0x00, 0x00, 0x82, 0xff
vertex   -111,   2053,    111,   -618,  -1793,   0x00, 0x00, 0x82, 0xff
vertex   -111,   2322,    111,   -618,  -2205,   0x00, 0x00, 0x82, 0xff
vertex   -335,   2322,   -335,   1082,  -1152,   0x00, 0x00, 0x81, 0xff
vertex   -111,   2322,   -335,    691,  -1152,   0x00, 0x00, 0x81, 0xff
vertex   -335,   1677,   -335,   1082,     18,   0x00, 0x00, 0x81, 0xff
vertex   -111,   2053,   -335,    691,   -664,   0x00, 0x00, 0x81, 0xff
vertex   -111,   2322,   -111,   -618,  -2205,   0x00, 0x51, 0x61, 0xff
vertex   -335,   2322,   -111,   -277,  -2205,   0x00, 0x50, 0x62, 0xff
vertex   -111,   2053,    111,   -618,  -1793,   0x00, 0x50, 0x61, 0xff
vertex   -335,   2051,    111,   -277,  -1791,   0x00, 0x50, 0x62, 0xff
vertex    111,   2322,    111,   -959,  -2205,   0x00, 0x52, 0xa0, 0xff
vertex    335,   2322,    111,  -1301,  -2205,   0x01, 0x51, 0x9f, 0xff
vertex    111,   2058,   -111,   -959,  -1801,   0x00, 0x52, 0xa0, 0xff
vertex    335,   2054,   -111,  -1301,  -1796,   0x01, 0x51, 0x9f, 0xff
vertex    111,   2322,   -111,   -959,  -2205,   0x00, 0x00, 0x7f, 0xff
vertex    111,   2058,   -111,   -959,  -1801,   0x00, 0x00, 0x7f, 0xff
vertex    335,   2322,   -111,  -1301,  -2205,   0x00, 0x00, 0x7f, 0xff
vertex    335,   2054,   -111,  -1301,  -1796,   0x00, 0x00, 0x7f, 0xff

wooden_signpost_vertex_1: /* 17 vertices out of 30 */
vertex    335,   1677,    111,    -89,     18,   0x00, 0x00, 0x82, 0xff
vertex    111,   1677,    111,    299,     18,   0x00, 0x00, 0x82, 0xff
vertex    335,   1946,    111,    -89,   -469,   0x00, 0x00, 0x82, 0xff
vertex   -111,   1946,    111,    691,   -469,   0x00, 0x00, 0x82, 0xff
vertex    111,   1677,   -335,    299,     18,   0x00, 0x00, 0x81, 0xff
vertex    111,   1946,   -335,    299,   -469,   0x00, 0x00, 0x81, 0xff
vertex    335,   1677,   -335,    -89,     18,   0x00, 0x00, 0x81, 0xff
vertex    335,   2322,   -335,    -89,  -1152,   0x00, 0x00, 0x81, 0xff
vertex    111,   2322,   -335,    299,  -1152,   0x00, 0x00, 0x81, 0xff
vertex    111,   2322,    335,    299,  -1152,   0x00, 0x00, 0x7f, 0xff
vertex    111,   2053,    335,    299,   -664,   0x00, 0x00, 0x7e, 0xff
vertex    335,   2322,    335,    -89,  -1152,   0x00, 0x00, 0x7e, 0xff
vertex    335,   1676,    336,    -89,     18,   0x00, 0x00, 0x7e, 0xff
vertex    111,   1677,    335,    302,     21,   0x00, 0x00, 0x7e, 0xff
vertex   -111,   2322,    111,    691,  -1152,   0x00, 0x00, 0x82, 0xff
vertex    111,   2053,    111,    299,   -664,   0x00, 0x00, 0x82, 0xff
vertex   -111,   2053,    111,    691,   -662,   0x00, 0x00, 0x82, 0xff

wooden_signpost_vertex_2: /* 18 vertices out of 30 */
vertex    111,   2053,    111,    299,   -664,   0x00, 0x00, 0x82, 0xff
vertex    111,   1946,    111,    299,   -469,   0x00, 0x00, 0x81, 0xff
vertex   -111,   1946,    111,    691,   -469,   0x00, 0x00, 0x82, 0xff
vertex   -111,   2053,   -111,    691,   -664,   0x00, 0x00, 0x7e, 0xff
vertex   -111,   1943,   -112,    691,   -463,   0x00, 0x00, 0x7e, 0xff
vertex    111,   2322,   -111,    299,  -1152,   0x00, 0x00, 0x7e, 0xff
vertex   -110,   1676,   -111,    687,     21,   0x00, 0x00, 0x7e, 0xff
vertex   -335,   1946,   -111,   1082,   -469,   0x00, 0x00, 0x7e, 0xff
vertex   -335,   1677,   -111,   1082,     18,   0x00, 0x00, 0x7f, 0xff
vertex   -335,   2322,    335,   1082,  -1152,   0x00, 0x00, 0x7f, 0xff
vertex   -335,   1677,    335,   1082,     18,   0x00, 0x00, 0x7f, 0xff
vertex   -111,   2322,    335,    691,  -1152,   0x00, 0x00, 0x7f, 0xff
vertex   -111,   1946,    335,    691,   -469,   0x00, 0x00, 0x7f, 0xff
vertex   -111,   1677,    335,    691,     18,   0x00, 0x00, 0x7f, 0xff
vertex    111,   1946,   -335,    299,   -469,   0x00, 0x00, 0x81, 0xff
vertex   -111,   1677,   -335,    691,     18,   0x00, 0x00, 0x81, 0xff
vertex   -111,   2053,   -335,    691,   -664,   0x00, 0x00, 0x81, 0xff
vertex   -335,   1677,   -335,   1082,     18,   0x00, 0x00, 0x81, 0xff

wooden_signpost_vertex_3: /* 22 vertices out of 30 */
vertex   -111,   2322,    335,    691,  -1152,   0x00, 0x00, 0x7f, 0xff
vertex   -111,   1946,    335,    691,   -469,   0x00, 0x00, 0x7f, 0xff
vertex    111,   2053,    335,    299,   -664,   0x00, 0x00, 0x7e, 0xff
vertex    111,   1677,    335,    302,     21,   0x00, 0x00, 0x7e, 0xff
vertex    111,   2322,   -335,    299,  -1152,   0x00, 0x00, 0x81, 0xff
vertex    111,   1946,   -335,    299,   -469,   0x00, 0x00, 0x81, 0xff
vertex   -111,   2053,   -335,    691,   -664,   0x00, 0x00, 0x81, 0xff
vertex    111,   1946,   -111,    299,   -469,   0x00, 0x00, 0x7f, 0xff
vertex    111,   2322,   -111,    299,  -1152,   0x00, 0x00, 0x7e, 0xff
vertex   -110,   1676,   -111,    687,     21,   0x00, 0x00, 0x7e, 0xff
vertex   -111,   2322,    111,    649,  -1056,   0x61, 0x51, 0x00, 0xff
vertex   -111,   2322,    335,    992,  -1056,   0x61, 0x51, 0x00, 0xff
vertex    111,   2053,    111,    649,   -630,   0x61, 0x51, 0x00, 0xff
vertex    111,   2053,    335,    992,   -630,   0x61, 0x51, 0x00, 0xff
vertex    111,   2322,   -335,    -32,  -1056,   0x9f, 0x51, 0x00, 0xff
vertex   -111,   2053,   -335,    -32,   -630,   0x9f, 0x51, 0x00, 0xff
vertex    111,   2322,   -111,    308,  -1056,   0x9f, 0x51, 0x00, 0xff
vertex   -111,   2053,   -111,    308,   -630,   0x9f, 0x51, 0x00, 0xff
vertex   -111,   1676,    110,    308,   -802,   0x00, 0xaf, 0x9f, 0xff
vertex   -335,   1676,    110,    649,   -802,   0xff, 0xb0, 0x9f, 0xff
vertex   -111,   1943,   -112,    308,  -1139,   0x00, 0xaf, 0x9f, 0xff
vertex   -335,   1946,   -111,    649,  -1139,   0xff, 0xb0, 0x9f, 0xff

wooden_signpost_vertex_4: /* 22 vertices out of 30 */
vertex    111,   1677,   -111,    -32,  -1139,   0xff, 0xaf, 0x61, 0xff
vertex    335,   1676,   -110,   -372,  -1136,   0x00, 0xb0, 0x61, 0xff
vertex    111,   1946,    111,    -32,   -800,   0x00, 0xaf, 0x61, 0xff
vertex    335,   1946,    111,   -372,   -800,   0x00, 0xb0, 0x61, 0xff
vertex    335,   1676,    336,    -32,    -32,   0x7f, 0x00, 0x00, 0xff
vertex    335,   1677,    111,    308,    -32,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2322,    335,    -32,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2322,    111,    308,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex    111,   2322,    111,    308,  -1056,   0x81, 0x00, 0x00, 0xff
vertex    111,   2053,    111,    308,   -630,   0x81, 0x00, 0x00, 0xff
vertex    111,   2322,    335,    -32,  -1056,   0x81, 0x00, 0x00, 0xff
vertex    111,   2053,    335,    -32,   -630,   0x81, 0x00, 0x00, 0xff
vertex    335,   2322,   -335,    992,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2322,   -111,    649,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex    335,   1677,   -335,    992,    -32,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2054,   -111,    649,   -631,   0x7f, 0x00, 0x00, 0xff
vertex    111,   1946,   -111,   -833,  -1463,   0x61, 0xb0, 0x00, 0xff
vertex   -110,   1676,   -111,   -494,  -1053,   0x61, 0xb0, 0x00, 0xff
vertex    111,   1946,   -335,   -833,  -1463,   0x61, 0xb0, 0x00, 0xff
vertex    111,   1946,   -335,   -833,  -1463,   0x61, 0xaf, 0xff, 0xff
vertex   -110,   1676,   -111,   -494,  -1053,   0x61, 0xaf, 0xff, 0xff
vertex   -111,   1677,   -335,   -493,  -1053,   0x61, 0xaf, 0xff, 0xff

wooden_signpost_vertex_5: /* 20 vertices out of 30 */
vertex    335,   2322,    111,    308,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex    335,   1946,    111,    308,   -459,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2054,   -111,    649,   -631,   0x7f, 0x00, 0x00, 0xff
vertex    335,   1676,   -110,    648,    -31,   0x7f, 0x00, 0x00, 0xff
vertex   -335,   1677,   -335,    992,    -32,   0x81, 0x00, 0x00, 0xff
vertex   -335,   1677,   -111,    649,    -32,   0x81, 0x00, 0x00, 0xff
vertex   -335,   2322,   -335,    992,  -1056,   0x81, 0x00, 0x00, 0xff
vertex   -335,   1946,   -111,    649,   -459,   0x81, 0x00, 0x00, 0xff
vertex    111,   1677,    111,   -833,  -1053,   0x9f, 0xaf, 0x00, 0xff
vertex    111,   1677,    335,   -833,  -1053,   0x9f, 0xaf, 0x00, 0xff
vertex   -111,   1946,    111,   -493,  -1463,   0x9f, 0xaf, 0x00, 0xff
vertex   -111,   1946,    335,   -493,  -1463,   0x9f, 0xaf, 0x00, 0xff
vertex   -111,   2322,   -335,    992,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   2322,   -111,    649,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   2053,   -335,    992,   -630,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   2053,   -111,    649,   -630,   0x7f, 0x00, 0x00, 0xff
vertex    111,   1677,   -111,  -1932,  -1254,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,    111,  -1932,  -1664,   0x81, 0x00, 0x00, 0xff
vertex    111,   1677,   -335,  -1932,  -1254,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,   -111,  -1932,  -1664,   0x81, 0x00, 0x00, 0xff

wooden_signpost_vertex_6: /* 16 vertices out of 30 */
vertex   -111,   1943,   -112,    651,   -453,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   2322,   -111,    649,  -1056,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1676,    110,    311,    -31,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1946,    111,    308,   -459,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   2053,    111,    310,   -628,   0x7f, 0x00, 0x00, 0xff
vertex   -335,   2322,    111,    308,  -1056,   0x81, 0x00, 0x00, 0xff
vertex   -335,   2051,    111,    310,   -626,   0x81, 0x00, 0x00, 0xff
vertex   -335,   2322,    335,    -32,  -1056,   0x81, 0x00, 0x00, 0xff
vertex   -335,   1677,    335,    -32,    -32,   0x81, 0x00, 0x00, 0xff
vertex   -335,   1676,    110,    311,    -31,   0x81, 0x00, 0x00, 0xff
vertex   -335,   2322,   -335,    992,  -1056,   0x81, 0x00, 0x00, 0xff
vertex   -335,   1946,   -111,    649,   -459,   0x81, 0x00, 0x00, 0xff
vertex   -335,   2322,   -111,    649,  -1056,   0x81, 0x00, 0x00, 0xff
vertex    335,   1676,   -110,    648,    -31,   0x7f, 0x00, 0x00, 0xff
vertex    335,   1677,   -335,    992,    -32,   0x7f, 0x00, 0x00, 0xff
vertex    335,   2054,   -111,    649,   -631,   0x7f, 0x00, 0x00, 0xff

wooden_signpost_vertex_7: /* 25 vertices out of 30 */
vertex    111,   2058,   -111,  -4539,  -6114,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,   -111,  -4539,  -5944,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,    111,  -4539,  -5944,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,    111,  -1932,  -1664,   0x81, 0x00, 0x00, 0xff
vertex    111,   2322,    111,  -1932,  -2238,   0x81, 0x00, 0x00, 0xff
vertex    111,   2058,   -111,  -1932,  -1834,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,   -111,   -833,  -1463,   0x81, 0x00, 0x00, 0xff
vertex    111,   1946,   -335,   -833,  -1463,   0x81, 0x00, 0x00, 0xff
vertex    111,   1677,   -335,   -833,  -1053,   0x81, 0x00, 0x00, 0xff
vertex   -111,   1677,    335,    -32,    -33,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1946,    111,    308,   -459,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1946,    335,    -32,   -459,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1677,    335,    -32,    -32,   0x7f, 0x00, 0x00, 0xff
vertex   -111,   1676,    110,    311,    -31,   0x7f, 0x00, 0x00, 0xff
vertex    111,   2322,    111,   1088,   -746,   0x00, 0x7e, 0x00, 0xff
vertex    110,   2321,    335,   1086,   -745,   0x00, 0x7e, 0x00, 0xff
vertex    335,   2322,    111,   1348,   -779,   0x00, 0x7e, 0x00, 0xff
vertex    335,   2322,    335,   1348,   -779,   0x00, 0x7e, 0x00, 0xff
vertex    335,   1677,    111,   1399,     93,   0x00, 0x82, 0x00, 0xff
vertex    335,   1676,    336,   1399,     92,   0x00, 0x82, 0x00, 0xff
vertex    111,   1677,    111,   1139,    126,   0x00, 0x82, 0x00, 0xff
vertex    111,   1677,    335,   1139,    124,   0x00, 0x82, 0x00, 0xff
vertex   -335,   1677,    335,   1139,    124,   0x00, 0x82, 0x00, 0xff
vertex   -335,   1676,    110,   1139,    126,   0x00, 0x82, 0x00, 0xff
vertex   -111,   1677,    335,   1399,     92,   0x00, 0x82, 0x00, 0xff

wooden_signpost_vertex_8: /* 22 vertices out of 30 */
vertex   -111,   1677,    335,   1399,     92,   0x00, 0x82, 0x00, 0xff
vertex   -335,   1676,    110,   1139,    126,   0x00, 0x82, 0x00, 0xff
vertex   -111,   1676,    110,   1399,     93,   0x00, 0x82, 0x00, 0xff
vertex    335,   1677,   -335,   1919,     26,   0x00, 0x82, 0x00, 0xff
vertex    335,   1676,   -110,   1920,     28,   0x00, 0x82, 0x00, 0xff
vertex    111,   1677,   -335,   1659,     59,   0x00, 0x82, 0x00, 0xff
vertex    111,   1677,   -111,   1659,     59,   0x00, 0x82, 0x00, 0xff
vertex   -111,   1677,   -335,   1399,     92,   0x00, 0x82, 0x00, 0xff
vertex   -110,   1676,   -111,   1402,     93,   0x00, 0x82, 0x00, 0xff
vertex   -335,   1677,   -335,   1139,    124,   0x00, 0x82, 0x00, 0xff
vertex   -335,   1677,   -111,   1139,    124,   0x00, 0x82, 0x00, 0xff
vertex    335,   2322,   -335,   1348,   -779,   0x00, 0x7e, 0x00, 0xff
vertex    111,   2322,   -335,   1088,   -746,   0x00, 0x7e, 0x00, 0xff
vertex    335,   2321,   -110,   1348,   -777,   0x00, 0x7e, 0x00, 0xff
vertex    111,   2322,   -111,   1088,   -746,   0x00, 0x7e, 0x00, 0xff
vertex   -335,   2322,   -111,    567,   -681,   0x00, 0x7e, 0x00, 0xff
vertex   -110,   2321,   -111,    830,   -712,   0x00, 0x7e, 0x00, 0xff
vertex   -335,   2322,   -335,    567,   -681,   0x00, 0x7e, 0x00, 0xff
vertex   -111,   2322,   -335,    827,   -712,   0x00, 0x7e, 0x00, 0xff
vertex   -335,   2322,    335,    567,   -681,   0x00, 0x7e, 0x00, 0xff
vertex   -111,   2322,    335,    827,   -712,   0x00, 0x7e, 0x00, 0xff
vertex   -335,   2321,    110,    567,   -679,   0x00, 0x7e, 0x00, 0xff

wooden_signpost_vertex_9: /* 3 vertices out of 3 */
vertex   -335,   2321,    110,    567,   -679,   0x00, 0x7e, 0x00, 0xff
vertex   -111,   2322,    335,    827,   -712,   0x00, 0x7e, 0x00, 0xff
vertex   -111,   2321,    110,    827,   -712,   0x00, 0x7e, 0x00, 0xff

/* Render order: 1 */

glabel wooden_signpost_dl_opaque
gsSPClearGeometryMode G_LIGHTING
/* g #LIGHTING #ENVMAP */
gsDPPipeSync
gsSPSetGeometryMode G_LIGHTING | G_TEXTURE_GEN
gsSPNumLights NUMLIGHTS_1
gsSPLight wooden_signpost_diffuse_light, 1
gsSPLight wooden_signpost_ambient_light, 2
gsDPSetCombineModeLERP G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPSetTextureFilter G_TF_BILERP
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock wooden_signpost_texture_0, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPTexture 1984, 1984, 0, 0, 1
gsDPTileSync
gsSPVertex wooden_signpost_vertex_0, 20, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
gsSP2Triangles 4, 5, 6, 0x00, 6, 5, 7, 0x00
gsSP2Triangles 8, 9, 10, 0x00, 10, 9, 11, 0x00
gsSP2Triangles 12, 13, 14, 0x00, 14, 13, 15, 0x00
gsSP2Triangles 16, 17, 18, 0x00, 18, 17, 19, 0x00
gsSPVertex wooden_signpost_vertex_1, 17, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
gsSP2Triangles 4, 5, 6, 0x00, 6, 5, 7, 0x00
gsSP2Triangles 5, 8, 7, 0x00, 9, 10, 11, 0x00
gsSP2Triangles 11, 10, 12, 0x00, 10, 13, 12, 0x00
gsSP2Triangles 14, 15, 16, 0x00, 16, 15, 3, 0x00
gsSPVertex wooden_signpost_vertex_2, 18, 0
gsSP2Triangles 0, 1, 2, 0x00, 3, 4, 5, 0x00
gsSP2Triangles 5, 4, 6, 0x00, 4, 7, 6, 0x00
gsSP2Triangles 6, 7, 8, 0x00, 9, 10, 11, 0x00
gsSP2Triangles 11, 10, 12, 0x00, 10, 13, 12, 0x00
gsSP2Triangles 14, 15, 16, 0x00, 16, 15, 17, 0x00
gsSPVertex wooden_signpost_vertex_3, 22, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
gsSP2Triangles 4, 5, 6, 0x00, 7, 8, 9, 0x00
/* r #LIGHTING #ENVMAP */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock wooden_signpost_texture_1, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP2Triangles 10, 11, 12, 0x00, 12, 11, 13, 0x00
gsSP2Triangles 14, 15, 16, 0x00, 16, 15, 17, 0x00
gsSP2Triangles 18, 19, 20, 0x00, 20, 19, 21, 0x00
gsSPVertex wooden_signpost_vertex_4, 22, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
/* b #LIGHTING #ENVMAP */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock wooden_signpost_texture_2, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP2Triangles 4, 5, 6, 0x00, 6, 5, 7, 0x00
gsSP2Triangles 8, 9, 10, 0x00, 10, 9, 11, 0x00
gsSP2Triangles 12, 13, 14, 0x00, 14, 13, 15, 0x00
gsSP2Triangles 16, 17, 18, 0x00, 19, 20, 21, 0x00
gsSPVertex wooden_signpost_vertex_5, 20, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
gsSP2Triangles 4, 5, 6, 0x00, 6, 5, 7, 0x00
gsSP2Triangles 8, 9, 10, 0x00, 10, 9, 11, 0x00
gsSP2Triangles 12, 13, 14, 0x00, 14, 13, 15, 0x00
gsSP2Triangles 16, 17, 18, 0x00, 18, 17, 19, 0x00
gsSPVertex wooden_signpost_vertex_6, 16, 0
gsSP2Triangles 0, 1, 2, 0x00, 2, 1, 3, 0x00
gsSP2Triangles 1, 4, 3, 0x00, 5, 6, 7, 0x00
gsSP2Triangles 7, 6, 8, 0x00, 6, 9, 8, 0x00
gsSP2Triangles 10, 11, 12, 0x00, 12, 11, 6, 0x00
gsSP2Triangles 11, 9, 6, 0x00, 13, 14, 15, 0x00
gsSPVertex wooden_signpost_vertex_7, 25, 0
gsSP2Triangles 0, 1, 2, 0x00, 3, 4, 5, 0x00
gsSP2Triangles 6, 7, 8, 0x00, 9, 10, 11, 0x00
gsSP1Triangle 10, 12, 13, 0x00
/* y #LIGHTING #ENVMAP */
gsDPPipeSync
gsDPSetTextureLUT G_TT_NONE
gsDPLoadTextureBlock wooden_signpost_texture_3, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_WRAP | G_TX_NOMIRROR,  G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsDPTileSync
gsSP2Triangles 14, 15, 16, 0x00, 16, 15, 17, 0x00
gsSP2Triangles 18, 19, 20, 0x00, 20, 19, 21, 0x00
gsSP1Triangle 22, 23, 24, 0x00
gsSPVertex wooden_signpost_vertex_8, 22, 0
gsSP2Triangles 0, 1, 2, 0x00, 3, 4, 5, 0x00
gsSP2Triangles 5, 4, 6, 0x00, 7, 8, 9, 0x00
gsSP2Triangles 9, 8, 10, 0x00, 11, 12, 13, 0x00
gsSP2Triangles 13, 12, 14, 0x00, 15, 16, 17, 0x00
gsSP2Triangles 17, 16, 18, 0x00, 19, 20, 21, 0x00
gsSPVertex wooden_signpost_vertex_9, 3, 0
gsSP1Triangle 0, 1, 2, 0x00
gsSPTexture -1, -1, 0, 0, 0
gsDPPipeSync
gsDPSetCombineModeLERP G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE, G_CCMUX_0, G_CCMUX_0, G_CCMUX_0, G_CCMUX_SHADE, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsSPSetGeometryMode G_LIGHTING
gsDPSetTextureLUT G_TT_NONE
gsSPClearGeometryMode G_TEXTURE_GEN
gsSPEndDisplayList
