# Generated by obsidian
Material1:
.incbin "levels/bob/Material1.rgba16"
Material:
.incbin "levels/bob/Material.rgba16"

ttt_vertex_0:
vertex -493, 0, 493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #1
vertex 0, -892, 697,    	-2563, -8570,    	99, 99, 99, 255  		# VERTEX #2
vertex -493, -892, 493,    	2563, -8570,    	87, 87, 87, 255  		# VERTEX #3
vertex 0, -892, 697,    	-2563, -8570,    	99, 99, 99, 255  		# VERTEX #4
vertex -493, 0, 493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #5
vertex 0, 0, 697,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #6
vertex -697, -892, 0,    	2563, -8570,    	84, 84, 84, 255  		# VERTEX #7
vertex -493, 0, 493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #8
vertex -493, -892, 493,    	-2563, -8570,    	87, 87, 87, 255  		# VERTEX #9
vertex -493, 0, 493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #10
vertex -697, -892, 0,    	2563, -8570,    	84, 84, 84, 255  		# VERTEX #11
vertex -697, 0, 0,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #12
vertex -493, -892, -493,    	2563, -8570,    	158, 158, 158, 255  		# VERTEX #13
vertex -697, 0, 0,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #14
vertex -697, -892, 0,    	-2563, -8570,    	84, 84, 84, 255  		# VERTEX #15

ttt_vertex_1:
vertex -697, 0, 0,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #16
vertex -493, -892, -493,    	2563, -8570,    	158, 158, 158, 255  		# VERTEX #17
vertex -493, 0, -493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #18
vertex 0, 0, -697,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #19
vertex -493, -892, -493,    	-2563, -8570,    	158, 158, 158, 255  		# VERTEX #20
vertex 0, -892, -697,    	2563, -8570,    	86, 86, 86, 255  		# VERTEX #21
vertex -493, -892, -493,    	-2563, -8570,    	158, 158, 158, 255  		# VERTEX #22
vertex 0, 0, -697,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #23
vertex -493, 0, -493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #24
vertex 493, 0, -493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #25
vertex 0, -892, -697,    	-2563, -8570,    	86, 86, 86, 255  		# VERTEX #26
vertex 493, -892, -493,    	2563, -8570,    	105, 105, 105, 255  		# VERTEX #27
vertex 0, -892, -697,    	-2563, -8570,    	86, 86, 86, 255  		# VERTEX #28
vertex 493, 0, -493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #29
vertex 0, 0, -697,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #30

ttt_vertex_2:
vertex 493, 0, -493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #31
vertex 697, -892, 0,    	2563, -8570,    	85, 85, 85, 255  		# VERTEX #32
vertex 697, 0, 0,    	2563, 0,    	114, 114, 114, 255  		# VERTEX #33
vertex 697, -892, 0,    	2563, -8570,    	85, 85, 85, 255  		# VERTEX #34
vertex 493, 0, -493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #35
vertex 493, -892, -493,    	-2563, -8570,    	105, 105, 105, 255  		# VERTEX #36
vertex 697, 0, 0,    	-2563, 0,    	114, 114, 114, 255  		# VERTEX #37
vertex 493, -892, 493,    	2563, -8570,    	85, 85, 85, 255  		# VERTEX #38
vertex 493, 0, 493,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #39
vertex 493, -892, 493,    	2563, -8570,    	85, 85, 85, 255  		# VERTEX #40
vertex 697, 0, 0,    	-2563, 0,    	114, 114, 114, 255  		# VERTEX #41
vertex 697, -892, 0,    	-2563, -8570,    	85, 85, 85, 255  		# VERTEX #42
vertex 0, 0, 697,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #43
vertex 493, -892, 493,    	-2563, -8570,    	85, 85, 85, 255  		# VERTEX #44
vertex 0, -892, 697,    	2563, -8570,    	99, 99, 99, 255  		# VERTEX #45

ttt_vertex_3:
vertex 493, -892, 493,    	-2563, -8570,    	85, 85, 85, 255  		# VERTEX #46
vertex 0, 0, 697,    	2563, 0,    	255, 255, 255, 255  		# VERTEX #47
vertex 493, 0, 493,    	-2563, 0,    	255, 255, 255, 255  		# VERTEX #48
vertex -155, -772, -155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #49
vertex 0, -892, -220,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #50
vertex -155, -892, -155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #51
vertex 0, -892, -220,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #52
vertex -155, -772, -155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #53
vertex 0, -772, -220,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #54
vertex -155, -772, -155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #55
vertex -220, -892, 0,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #56
vertex -220, -772, 0,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #57
vertex -220, -892, 0,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #58
vertex -155, -772, -155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #59
vertex -155, -892, -155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #60

ttt_vertex_4:
vertex -220, -772, 0,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #61
vertex -155, -892, 155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #62
vertex -155, -772, 155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #63
vertex -155, -892, 155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #64
vertex -220, -772, 0,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #65
vertex -220, -892, 0,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #66
vertex 0, -772, 220,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #67
vertex -155, -892, 155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #68
vertex 0, -892, 220,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #69
vertex -155, -892, 155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #70
vertex 0, -772, 220,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #71
vertex -155, -772, 155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #72
vertex 155, -772, 155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #73
vertex 0, -892, 220,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #74
vertex 155, -892, 155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #75

ttt_vertex_5:
vertex 0, -892, 220,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #76
vertex 155, -772, 155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #77
vertex 0, -772, 220,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #78
vertex 220, -892, 0,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #79
vertex 155, -772, 155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #80
vertex 155, -892, 155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #81
vertex 155, -772, 155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #82
vertex 220, -892, 0,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #83
vertex 220, -772, 0,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #84
vertex 155, -892, -155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #85
vertex 220, -772, 0,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #86
vertex 220, -892, 0,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #87
vertex 220, -772, 0,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #88
vertex 155, -892, -155,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #89
vertex 155, -772, -155,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #90

ttt_vertex_6:
vertex 0, -772, -220,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #91
vertex 155, -892, -155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #92
vertex 0, -892, -220,    	810, -8570,    	255, 255, 255, 255  		# VERTEX #93
vertex 155, -892, -155,    	-810, -8570,    	255, 255, 255, 255  		# VERTEX #94
vertex 0, -772, -220,    	810, -7418,    	255, 255, 255, 255  		# VERTEX #95
vertex 155, -772, -155,    	-810, -7418,    	255, 255, 255, 255  		# VERTEX #96
vertex -493, -892, 493,    	-4736, -4736,    	255, 255, 255, 255  		# VERTEX #97
vertex -493, -892, -493,    	-4736, 4736,    	255, 255, 255, 255  		# VERTEX #98
vertex -697, -892, 0,    	-6698, 0,    	255, 255, 255, 255  		# VERTEX #99
vertex -493, -892, -493,    	-4736, 4736,    	255, 255, 255, 255  		# VERTEX #100
vertex -493, -892, 493,    	-4736, -4736,    	255, 255, 255, 255  		# VERTEX #101
vertex 0, -892, 697,    	0, -6698,    	255, 255, 255, 255  		# VERTEX #102
vertex -493, -892, -493,    	-4736, 4736,    	255, 255, 255, 255  		# VERTEX #103
vertex 0, -892, 697,    	0, -6698,    	255, 255, 255, 255  		# VERTEX #104
vertex -220, -892, 0,    	-2117, 0,    	255, 255, 255, 255  		# VERTEX #105

ttt_vertex_7:
vertex -220, -892, 0,    	-2117, 0,    	255, 255, 255, 255  		# VERTEX #106
vertex 0, -892, 697,    	0, -6698,    	255, 255, 255, 255  		# VERTEX #107
vertex -155, -892, 155,    	-1497, -1497,    	255, 255, 255, 255  		# VERTEX #108
vertex -155, -892, 155,    	-1497, -1497,    	255, 255, 255, 255  		# VERTEX #109
vertex 0, -892, 697,    	0, -6698,    	255, 255, 255, 255  		# VERTEX #110
vertex 0, -892, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #111
vertex 0, -892, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #112
vertex 0, -892, 697,    	0, -6698,    	255, 255, 255, 255  		# VERTEX #113
vertex 493, -892, 493,    	4736, -4736,    	255, 255, 255, 255  		# VERTEX #114
vertex 0, -892, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #115
vertex 493, -892, 493,    	4736, -4736,    	255, 255, 255, 255  		# VERTEX #116
vertex 155, -892, 155,    	1497, -1497,    	255, 255, 255, 255  		# VERTEX #117
vertex 155, -892, 155,    	1497, -1497,    	255, 255, 255, 255  		# VERTEX #118
vertex 493, -892, 493,    	4736, -4736,    	255, 255, 255, 255  		# VERTEX #119
vertex 220, -892, 0,    	2117, 0,    	255, 255, 255, 255  		# VERTEX #120

ttt_vertex_8:
vertex -220, -892, 0,    	-2117, 0,    	255, 255, 255, 255  		# VERTEX #121
vertex 0, -892, -697,    	0, 6698,    	255, 255, 255, 255  		# VERTEX #122
vertex -493, -892, -493,    	-4736, 4736,    	255, 255, 255, 255  		# VERTEX #123
vertex 0, -892, -697,    	0, 6698,    	255, 255, 255, 255  		# VERTEX #124
vertex -220, -892, 0,    	-2117, 0,    	255, 255, 255, 255  		# VERTEX #125
vertex -155, -892, -155,    	-1497, 1497,    	255, 255, 255, 255  		# VERTEX #126
vertex 0, -892, -697,    	0, 6698,    	255, 255, 255, 255  		# VERTEX #127
vertex -155, -892, -155,    	-1497, 1497,    	255, 255, 255, 255  		# VERTEX #128
vertex 0, -892, -220,    	0, 2117,    	255, 255, 255, 255  		# VERTEX #129
vertex 0, -892, -697,    	0, 6698,    	255, 255, 255, 255  		# VERTEX #130
vertex 0, -892, -220,    	0, 2117,    	255, 255, 255, 255  		# VERTEX #131
vertex 155, -892, -155,    	1497, 1497,    	255, 255, 255, 255  		# VERTEX #132
vertex 0, -892, -697,    	0, 6698,    	255, 255, 255, 255  		# VERTEX #133
vertex 155, -892, -155,    	1497, 1497,    	255, 255, 255, 255  		# VERTEX #134
vertex 493, -892, -493,    	4736, 4736,    	255, 255, 255, 255  		# VERTEX #135

ttt_vertex_9:
vertex 493, -892, -493,    	4736, 4736,    	255, 255, 255, 255  		# VERTEX #136
vertex 155, -892, -155,    	1497, 1497,    	255, 255, 255, 255  		# VERTEX #137
vertex 220, -892, 0,    	2117, 0,    	255, 255, 255, 255  		# VERTEX #138
vertex 493, -892, -493,    	4736, 4736,    	255, 255, 255, 255  		# VERTEX #139
vertex 220, -892, 0,    	2117, 0,    	255, 255, 255, 255  		# VERTEX #140
vertex 493, -892, 493,    	4736, -4736,    	255, 255, 255, 255  		# VERTEX #141
vertex 493, -892, -493,    	4736, 4736,    	255, 255, 255, 255  		# VERTEX #142
vertex 493, -892, 493,    	4736, -4736,    	255, 255, 255, 255  		# VERTEX #143
vertex 697, -892, 0,    	6698, 0,    	255, 255, 255, 255  		# VERTEX #144
vertex -155, -772, 155,    	-1497, -1497,    	255, 255, 255, 255  		# VERTEX #145
vertex -155, -772, -155,    	-1497, 1497,    	255, 255, 255, 255  		# VERTEX #146
vertex -220, -772, 0,    	-2117, 0,    	255, 255, 255, 255  		# VERTEX #147
vertex -155, -772, -155,    	-1497, 1497,    	255, 255, 255, 255  		# VERTEX #148
vertex -155, -772, 155,    	-1497, -1497,    	255, 255, 255, 255  		# VERTEX #149
vertex 0, -772, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #150

ttt_vertex_10:
vertex -155, -772, -155,    	-1497, 1497,    	255, 255, 255, 255  		# VERTEX #151
vertex 0, -772, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #152
vertex 0, -772, -220,    	0, 2117,    	255, 255, 255, 255  		# VERTEX #153
vertex 0, -772, -220,    	0, 2117,    	255, 255, 255, 255  		# VERTEX #154
vertex 0, -772, 220,    	0, -2117,    	255, 255, 255, 255  		# VERTEX #155
vertex 155, -772, 155,    	1497, -1497,    	255, 255, 255, 255  		# VERTEX #156
vertex 0, -772, -220,    	0, 2117,    	255, 255, 255, 255  		# VERTEX #157
vertex 155, -772, 155,    	1497, -1497,    	255, 255, 255, 255  		# VERTEX #158
vertex 155, -772, -155,    	1497, 1497,    	255, 255, 255, 255  		# VERTEX #159
vertex 155, -772, -155,    	1497, 1497,    	255, 255, 255, 255  		# VERTEX #160
vertex 155, -772, 155,    	1497, -1497,    	255, 255, 255, 255  		# VERTEX #161
vertex 220, -772, 0,    	2117, 0,    	255, 255, 255, 255  		# VERTEX #162

ttt_dl:
gsDPPipeSync
gsDPSetCombineMode1Cycle G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPLoadTextureBlock Material1, 32, 32, 0, G_IM_FMT_RGBA, G_IM_SIZ_16b, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSPVertex ttt_vertex_0 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_1 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_2 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_3 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_4 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_5 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_6 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsDPPipeSync
gsDPSetCombineMode1Cycle G_CCMUX_TEXEL0, G_CCMUX_0, G_CCMUX_SHADE, G_CCMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_0, G_ACMUX_SHADE
gsDPLoadTextureBlock Material, 32, 32, 0, G_IM_FMT_RGBA, G_IM_SIZ_16b, G_TX_WRAP | G_TX_NOMIRROR, G_TX_WRAP | G_TX_NOMIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_7 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_8 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_9 15, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSP1Triangle 12, 13, 14
gsSPVertex ttt_vertex_10 12, 0
gsSP1Triangle 0, 1, 2
gsSP1Triangle 3, 4, 5
gsSP1Triangle 6, 7, 8
gsSP1Triangle 9, 10, 11
gsSPEndDisplayList
